#TODO: Force DaemonSet to not run on master.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kubevirt-csi-node
  namespace: kubevirt-csi-driver
spec:
  selector:
    matchLabels:
      app: kubevirt-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubevirt-csi-driver
    spec:
#      serviceAccount: kubevirt-csi-node-sa
      containers:
        - name: csi-driver-registrar
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/kubevirt.io/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: kubevirt-csi-driver
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          image: quay.io/kubevirt/csi-driver:latest
          args:
            - "--endpoint=unix:/csi/csi.sock"
            - "--namespace=kubevirt-csi-driver"
            - "--node-name=$(KUBE_NODE_NAME)"
            - "--infra-cluster-namespace=$(INFRACLUSTER_NAMESPACE)"
            - "--infra-cluster-api-url=$(INFRACLUSTER_API_URL)"
            - "--infra-cluster-token=/var/run/secrets/infracluster/token"
            - "--infra-cluster-ca=/var/run/secrets/infracluster/ca.crt"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFRACLUSTER_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: infra-cluster-sa-secret
                  key: namespace
            - name: INFRACLUSTER_API_URL
              valueFrom:
                secretKeyRef:
                  name: infra-cluster-sa-secret
                  key: apiUrl
          volumeMounts:
            - name: infracluster
              mountPath: "/var/run/secrets/infracluster"
            - name: socket-dir
              mountPath: /csi
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
            - name: host-dev
              mountPath: /dev
            - name: udev
              mountPath: /run/udev
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: infracluster
            secret:
              secretName: infra-cluster-sa-secret
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubevirt.io/
            type: DirectoryOrCreate
        - name: host-dev
          hostPath:
            path: /dev
        - name: udev
          hostPath:
            path: /run/udev
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
