kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kubevirt-csi-plugin
  namespace: kubevirt-csi-driver
spec:
  serviceName: "kubevirt-csi-driver"
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubevirt-csi-driver
    spec:
#      serviceAccount: kubevirt-csi-controller-sa
      containers:
        - name: csi-external-attacher
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-attacher:v2.0.0
          args:
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-provisioner:v1.5.0
          args:
            - "--v=9"
            - "--csi-address=/csi/csi.sock"
            - "--provisioner=csi.kubevirt.io"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: kubevirt-csi-driver
          imagePullPolicy: Always
          image: quay.io/kubevirt/csi-driver:latest
          args:
            - "--endpoint=unix:/csi/csi.sock"
            - "--namespace=kubevirt-csi-driver"
            - "--infra-cluster-namespace=$(INFRACLUSTER_NAMESPACE)"
            - "--infra-cluster-api-url=$(INFRACLUSTER_API_URL)"
            - "--infra-cluster-token=/var/run/secrets/infracluster/token"
            - "--infra-cluster-ca=/var/run/secrets/infracluster/ca.crt"
          ports:
          - containerPort: 9808
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 30
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFRACLUSTER_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: infra-cluster-sa-secret
                  key: namespace
            - name: INFRACLUSTER_API_URL
              valueFrom:
                secretKeyRef:
                  name: infra-cluster-sa-secret
                  key: apiUrl
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: infracluster
              mountPath: "/var/run/secrets/infracluster"
        - name: liveness-probe
          imagePullPolicy: Always
          image: quay.io/k8scsi/livenessprobe:v2.0.0
          args:
           - "--v=5"
           - "--csi-address=/csi/csi.sock"
           - "--health-port=9808"
           - "--probe-timeout=3s"
          volumeMounts:
           - mountPath: /csi
             name: socket-dir
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: infracluster
            secret:
              secretName: infra-cluster-sa-secret
